server:
  port: 8383
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eatup
    username: postgres
    password: sa
    driverClassName: org.postgresql.Driver
  application:
    name: auth-server
  profiles:
    active: native
  cloud:
    config:
      server:
        profile: native
        uri: http://localhost:8888/
  jpa:
    hibernate:
      hbm2ddl:
        auto: update
      ejb:
        naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
      default_schema: dental
  liquibase:
    changelog: classpath:/db/db.changelog-master.xml
    enabled: true
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      

gateway:
  ip: 192.168.1.35
  
 
token:
  expirationTime: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739
login:
  url:
    path: /users/login
    

logging:
  file: users-ws.log